retailer: farmacias-similares
categories:
  - id: aparato-respiratorio
    department: Aparato respiratorio
    name: Aparato respiratorio
    subcategory: Aparato respiratorio
    sub_subcategory: null
    url: https://www.farmaciasdesimilares.com/aparato-respiratorio/aparato-respiratorio
    enabled: true
