locations:
  - id: cdmx
    city: Ciudad de México
    state: CDMX
    country: México
    postal_code: null
    store: null
    store_id: null
    enabled: true

  - id: sc-toreo
    city: Miguel Hidalgo
    state: CDMX
    country: México
    postal_code: "11220"
    store: SC Toreo
    store_id: "2344"
    enabled: true

  - id: chedraui-polanco
    city: Miguel Hidalgo
    state: CDMX
    country: México
    postal_code: "11500"
    store: Chedraui Selecto México Polanco
    store_id: "232"
    enabled: true

  - id: fg-online
    city: Catálogo online
    state: Nacional
    country: México
    postal_code: null
    store: null
    store_id: null
    enabled: true

  - id: fahorro-online
    city: Catálogo online
    state: Nacional
    country: México
    postal_code: null
    store: null
    store_id: null
    enabled: true
