retailer: bodega-aurrera
categories:
  - id: cuidado-bucal
    department: Cuidado personal
    name: Cuidado bucal
    subcategory: null
    sub_subcategory: null
    url: https://www.bodegaaurrera.com.mx/content/cuidado-personal/cuidado-bucal/264479_950014
    enabled: true

  - id: cuidado-de-la-ropa
    department: Limpieza del hogar y cuidado de la ropa
    name: Cuidado de la ropa
    subcategory: null
    sub_subcategory: null
    url: https://www.bodegaaurrera.com.mx/content/cuidado-de-la-ropa/3680083
    enabled: true
