retailer: bodega-aurrera
categories:
  - id: cuidado-bucal
    department: Belleza y cuidado personal
    name: Higiene y cuidado personal
    subcategory: Cuidado bucal
    sub_subcategory: null
    url: https://despensa.bodegaaurrera.com.mx/browse/higiene-personal-y-belleza/cuidado-bucal/10_1004
    enabled: true
