retailer: farmacias-san-pablo
categories:
  - id: descongestionantes
    department: Medicamentos
    name: Gripe y tos
    subcategory: Descongestionantes
    sub_subcategory: null
    url: https://www.farmaciasanpablo.com.mx/medicamentos/gripe-y-tos/descongestionantes/
    enabled: true

  - id: preservativos
    department: Salud sexual
    name: Bienestar sexual
    subcategory: Preservativos
    sub_subcategory: null
    url: https://www.farmaciasanpablo.com.mx/salud-sexual/bienestar-sexual/preservativos/
    enabled: true

  - id: enjuagues-bucales
    department: Cuidado personal y belleza
    name: Cuidado bucal
    subcategory: Enjuagues bucales
    sub_subcategory: null
    url: https://www.farmaciasanpablo.com.mx/cuidado-personal-y-belleza/cuidado-bucal/enjuagues-bucales/
    enabled: true

  - id: pastas-dentales
    department: Cuidado personal y belleza
    name: Cuidado bucal
    subcategory: Pastas dentales
    sub_subcategory: null
    url: https://www.farmaciasanpablo.com.mx/cuidado-personal-y-belleza/cuidado-bucal/pastas-dentales/
    enabled: true
