from __future__ import annotations

import base64
import json
from datetime import datetime
from urllib.parse import parse_qs, urlencode, urlsplit, urlunsplit

from ..config import Category, Location
from ..parsers import absolute_url, clean_text
from .chedraui import ChedrauiBlocked, ChedrauiStoreContextError
from .chedraui_polanco import ChedrauiScraper as PolancoUIScraper


class ChedrauiScraper(PolancoUIScraper):
    """Polanco scraper with a public VTEX productSearchV3 gap fallback.

    Chedraui's HTML pagination can intermittently render an empty page while
    adjacent ranges are available. We keep the normal storefront as the primary
    source, but capture the exact productSearchV3 request generated by that
    storefront and replay only a missing range in the same verified browser
    context. No authentication or access-control mechanism is bypassed.
    """

    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self._product_search_template_url: str | None = None

    def _capture_product_search_request(self, request) -> None:
        url = request.url
        if "operationName=productSearchV3" in url:
            self._product_search_template_url = url

    def _collect_pages(self, page, category: Category, location: Location):
        page.on("request", self._capture_product_search_request)
        return super()._collect_pages(page, category, location)

    @staticmethod
    def _rewrite_product_search_range(url: str, start: int, end: int) -> str:
        parts = urlsplit(url)
        qs = parse_qs(parts.query, keep_blank_values=True)
        extensions = json.loads(qs["extensions"][0])
        encoded = extensions.get("variables")
        if not encoded:
            raise ValueError("productSearchV3 no contiene variables persistidas")
        variables = json.loads(base64.b64decode(encoded).decode("utf-8"))
        variables["from"] = start
        variables["to"] = end
        extensions["variables"] = base64.b64encode(
            json.dumps(variables, separators=(",", ":"), ensure_ascii=False).encode("utf-8")
        ).decode("ascii")
        flat = {key: values[-1] for key, values in qs.items()}
        flat["extensions"] = json.dumps(extensions, separators=(",", ":"))
        return urlunsplit((parts.scheme, parts.netloc, parts.path, urlencode(flat), parts.fragment))

    @staticmethod
    def _best_offer(product: dict) -> tuple[float | None, float | None, int | None, list[str]]:
        offers: list[tuple[int, float | None, float | None, int | None, list[str]]] = []
        for item in product.get("items") or []:
            if not isinstance(item, dict):
                continue
            for seller in item.get("sellers") or []:
                if not isinstance(seller, dict):
                    continue
                offer = seller.get("commertialOffer") or {}
                if not isinstance(offer, dict):
                    continue
                price = offer.get("Price")
                regular = offer.get("ListPrice")
                available = offer.get("AvailableQuantity")
                priority = 0 if seller.get("sellerDefault") else 1
                promo_names: list[str] = []
                for value in offer.get("discountHighlights") or []:
                    if isinstance(value, dict) and value.get("name"):
                        promo_names.append(str(value["name"]))
                for teaser in offer.get("teasers") or []:
                    if isinstance(teaser, dict) and teaser.get("name"):
                        promo_names.append(str(teaser["name"]))
                offers.append((priority, price, regular, available, promo_names))

        usable = [
            value for value in offers
            if value[1] is not None and float(value[1]) > 0 and (value[3] is None or int(value[3]) > 0)
        ]
        if not usable:
            usable = [value for value in offers if value[1] is not None and float(value[1]) > 0]
        if usable:
            usable.sort(key=lambda value: value[0])
            _, price, regular, available, promo_names = usable[0]
            return (
                float(price) if price is not None else None,
                float(regular) if regular is not None else None,
                int(available) if available is not None else None,
                promo_names,
            )

        price_range = product.get("priceRange") or {}
        if not isinstance(price_range, dict):
            price_range = {}
        selling_range = price_range.get("sellingPrice") or {}
        list_range = price_range.get("listPrice") or {}
        if not isinstance(selling_range, dict):
            selling_range = {}
        if not isinstance(list_range, dict):
            list_range = {}
        selling = selling_range.get("lowPrice")
        regular = list_range.get("lowPrice")
        return (
            float(selling) if selling is not None else None,
            float(regular) if regular is not None else None,
            None,
            [],
        )

    def _rows_from_product_search_payload(
        self,
        payload: dict,
        category: Category,
        location: Location,
    ) -> tuple[list[dict], int | None]:
        search = (payload.get("data") or {}).get("productSearch") or {}
        products = search.get("products") or []
        records_filtered = search.get("recordsFiltered")
        now = datetime.now().astimezone().isoformat(timespec="seconds")
        rows: list[dict] = []

        for product in products:
            if not isinstance(product, dict):
                continue
            sku = clean_text(str(product.get("productId") or product.get("productReference") or ""))
            name = clean_text(product.get("productName"))
            url = absolute_url(product.get("link"), "https://www.chedraui.com.mx/")
            if not sku or not name or not url:
                continue

            current, regular, available, promo_names = self._best_offer(product)
            if current is None:
                continue
            if regular is None or regular <= 0:
                regular = current
            if current > regular:
                current, regular = regular, current
            if current < regular and not promo_names:
                promo_names.append("Precio promocional")

            rows.append(
                {
                    "scrape_timestamp": now,
                    "retailer": "Chedraui",
                    "city": location.city,
                    "state": location.state,
                    "postal_code": location.postal_code,
                    "store": location.store,
                    "store_id": location.store_id,
                    "department": category.department,
                    "category": category.name,
                    "subcategory": category.subcategory,
                    "sub_subcategory": category.sub_subcategory,
                    "category_id": category.id,
                    "sku": sku,
                    "brand": clean_text(product.get("brand")) or self._infer_brand(name),
                    "product": name,
                    "price_current": current,
                    "price_regular": regular,
                    "promotion": clean_text(" | ".join(dict.fromkeys(promo_names))),
                    "pickup_available": available is None or available > 0,
                    "store_context_verified": True,
                    "store_context_method": f"{self._active_store_context_method}+productSearchV3",
                    "url": url,
                    "price_raw": f"productSearchV3 Price={current} ListPrice={regular}",
                }
            )

        return rows, int(records_filtered) if records_filtered is not None else None

    def _recover_page_from_product_search(
        self,
        page,
        category: Category,
        location: Location,
        page_number: int,
    ) -> tuple[list[dict], dict]:
        info: dict = {"mode": "productSearchV3", "rows": 0}
        template = self._product_search_template_url
        if not template:
            info["reason"] = "template_not_captured"
            return [], info

        start = (page_number - 1) * 20
        end = start + 19
        try:
            url = self._rewrite_product_search_range(template, start, end)
            response = page.context.request.get(url, timeout=120_000)
            info["status"] = response.status
            if response.status != 200:
                info["reason"] = f"http_{response.status}"
                return [], info
            payload = response.json()
            rows, records_filtered = self._rows_from_product_search_payload(payload, category, location)
            info["rows"] = len(rows)
            info["records_filtered"] = records_filtered
            info["from"] = start
            info["to"] = end
            return rows, info
        except Exception as exc:
            info["reason"] = f"api_error:{type(exc).__name__}"
            return [], info

    def _load_page_rows(self, page, category, location, page_number: int, target_rows: int | None):
        url, rows, attempts = super()._load_page_rows(
            page, category, location, page_number, target_rows
        )
        if rows:
            return url, rows, attempts

        recovered, api_info = self._recover_page_from_product_search(
            page, category, location, page_number
        )
        attempts.append(api_info)
        if recovered:
            self.run_meta.setdefault("api_recovered_pages", []).append(page_number)
        return url, recovered, attempts


__all__ = [
    "ChedrauiBlocked",
    "ChedrauiStoreContextError",
    "ChedrauiScraper",
]
